language: php

sudo: required

matrix:
  include:
    - php: 7.2
      env: SW_VERSION="4.4.14"
    - php: 7.3
      env: SW_VERSION="4.4.14"
    - php: 7.4
      env: SW_VERSION="4.4.14"
    - php: master
      env: SW_VERSION="4.4.14"

  allow_failures:
    - php: master

services:
  - mysql
  - redis
  - docker

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

install:
  - cd $TRAVIS_BUILD_DIR
  - bash .travis/swoole.install.sh
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv config-add .travis/ci.ini
  - bash .travis/setup.mysql.sh
  - docker run -d --name dev-consul -e CONSUL_BIND_INTERFACE=eth0 -p 8500:8500 consul

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer config -g process-timeout 900 && composer update

script:
  - composer analyse src/di src/json-rpc src/tracer src/metric src/redis src/nats src/db src/retry
  - composer test -- --exclude-group NonCoroutine
  - vendor/bin/phpunit --group NonCoroutine