version: '3.7'
services:
  hyperf-xcx:
    image: $REGISTRY_URL/$PROJECT_NAME:master
    environment:
      - "APP_PROJECT=hyperf-xcx"
      - "APP_ENV=master"
    ports:
      - 9501:9501
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 2
        delay: 5s
        order: start-first
    networks:
      - default-network
    configs:
      - source: hyperf-xcx
        target: /opt/www/.env
configs:
  hyperf-xcx:
    external: true
networks:
  default-network:
    external: true
